name: Suggest new Recommend Forum item
description: Informatino about the item you suggest
labels: [Contribution]
body
- type: markdown
  attributes:
    value: |
      Thank you for your interest on Forumate!
      
      Before you submit your issue, please complete each text area below with the relevant details for your bug, and complete the steps in the checklist
- type: input
  attributes:
    label: Link
    description: The new recommend forum item you suggest to add
    placeholder: "'https://example.com' for example"
  validations:
    required: true
- type: textarea
  attributes:
    label: Description
    description: |
      A short description of the forum. And why you'd like to suggest it as a build-in recommend forum.
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Checklist
    options:
    - label: This issue hasn't been addressed in an [existing GitHub issue](https://github.com/Kyle-Ye/Forumate/issues).
      required: true
