/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, November 5, 2019 at 2:51:05 AM Mountain Standard Time
* Operating System: Version 13.0 (Build 17J586)
* Image Source: /System/Library/Frameworks/WebKit.framework/WebKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

//#import <UIKit/UIScrollViewDelegate.h>
//#import <UIKit/UIResponderStandardEditActions.h>

@interface WKWebView : UIView <UIScrollViewDelegate, UIResponderStandardEditActions> {
    @property (assign,nonatomic,__weak) id<WKNavigationDelegate> navigationDelegate;
    @property (nonatomic,readonly) UIScrollView * scrollView;
}
-(void)setOpaque:(BOOL)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setBackgroundColor:(id)arg1 ;
-(id)loadHTMLString:(id)arg1 baseURL:(id)arg2 ;
@end
